Added in-toto Favicon
DarikshaAnsari/in-toto-docs pull request #25
Opened 2024-08-27 05:22 UTC by DarikshaAnsari

- Fixes :- #24

2024-08-27 05:23 UTC, DarikshaAnsari commented
@chalin PTAL!!

2024-08-27 09:28 UTC, lukpueh reviewed
Looks good. Any reason, you didn't include the standard 16x16 favicon? 

See opentelemtry for reference:
https://github.com/open-telemetry/opentelemetry.io/blob/main/layouts/partials/favicons.html
https://github.com/open-telemetry/opentelemetry.io/tree/main/static/favicons

2024-08-27 09:38 UTC, DarikshaAnsari commented
> Looks good. Any reason, you didn't include the standard 16x16 favicon?
> 
> See opentelemtry for reference: https://github.com/open-telemetry/opentelemetry.io/blob/main/layouts/partials/favicons.html https://github.com/open-telemetry/opentelemetry.io/tree/main/static/favicons

I'm not sure. I used [this icon generator](http://cthedot.de/icongen), which gave me a zip folder containing only specific sizes. If you'd like, I can include all the sizes with reference to OTEL.

2024-08-27 09:49 UTC, lukpueh commented
> I'm not sure. I used [this icon generator](http://cthedot.de/icongen), which gave me a zip folder containing only specific sizes. If you'd like, I can include all the sizes with reference to OTEL.

Not sure, if that's necessary. @chalin?

I suggest you let cthedot generate the default icons (the ones that are already selected):
```
favicon.ico
16x16 only, add to website root but do not add to HTML

PWA Progressive Web Apps
192x192 512x512 + maskable 192x192 512x512

apple touch icon
180x180
```

Also, in case you didn't already do that, you can use this svg as base image: https://github.com/cncf/artwork/blob/main/projects/in-toto/icon/color/in-toto-icon-color.svg

2024-08-27 10:08 UTC, DarikshaAnsari commented
see i have done this but this is not generating the desired output just check once.

2024-08-27 10:10 UTC, lukpueh commented
Weird, when I do it, I get this zip:

[icongen.zip](https://github.com/user-attachments/files/16760411/icongen.zip)

2024-08-27 10:30 UTC, DarikshaAnsari commented
Now I have added all the files of the zip that you've provided.

2024-08-28 00:32 UTC, chalin requested changes
Nice to see the favicon ✨. The set of icon files included seems fine.

See inline comments for a file to be dropped.

2024-08-28 00:32 UTC, chalin commented on static/favicons/_head.html
Drop this file, unless you know that it is being used, and if so explain why you believe so.

2024-08-28 00:32 UTC, chalin commented on layouts/partials/favicons.html
> +{{/* Docsy-delta */ -}}
Let's keep a note about how these were generated:

```suggestion
{{/* Docsy-delta

Icons generated by https://cthedot.de/icongen
from https://github.com/cncf/artwork/blob/main/projects/in-toto/icon/color/in-toto-icon-color.svg
*/ -}}
```

2024-08-28 00:32 UTC, chalin commented on layouts/partials/favicons.html
> +<!-- Android Icons -->
```suggestion
```

2024-08-28 00:32 UTC, chalin commented on layouts/partials/favicons.html
> +<!-- Android Maskable Icons -->
```suggestion
```

2024-08-28 15:02 UTC, lukpueh approved these changes

2024-08-28 17:25 UTC, chalin approved these changes

2024-08-28 17:26 UTC, merged